/*
 * UpdateAuthorReferenceReferencePositionDialog.java
 *
 * Created on 27-may-2011, 19:09:04
 */
package scimat.gui.components.editdialog;

import javax.swing.SpinnerNumberModel;
import scimat.gui.commands.edit.update.UpdateAuthorReferenceReferencePositionEdit;
import scimat.gui.commands.task.PerformKnowledgeBaseEditTask;
import scimat.model.knowledgebase.entity.AuthorReferenceReference;

/**
 *
 * @author mjcobo
 */
public class UpdateAuthorReferenceReferencePositionDialog extends javax.swing.JDialog {

  /** Creates new form UpdateDocumentAuthorPositionDialog */
  public UpdateAuthorReferenceReferencePositionDialog(java.awt.Frame parent) {
    super(parent, true);
    initComponents();
  }
  
  /**
   * 
   * @param authorReferenceReference 
   */
  public void refreshData(AuthorReferenceReference authorReferenceReference) {
  
    this.authorReferenceReference = authorReferenceReference;
    
    this.newPositionSpinner.getModel().setValue(authorReferenceReference.getPosition());
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    newPositionDescriptionLabel = new javax.swing.JLabel();
    newPositionSpinner = new javax.swing.JSpinner();
    separator = new javax.swing.JSeparator();
    updateButton = new javax.swing.JButton();
    cancelButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    newPositionDescriptionLabel.setText("New position:");

    newPositionSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

    updateButton.setText("Update");
    updateButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        updateButtonActionPerformed(evt);
      }
    });

    cancelButton.setText("Cancel");
    cancelButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(newPositionDescriptionLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(newPositionSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(105, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(separator, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(updateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton)))
            .addContainerGap())))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(newPositionDescriptionLabel)
          .addComponent(newPositionSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cancelButton)
          .addComponent(updateButton))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * 
   * @param evt 
   */
  private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
    
    (new PerformKnowledgeBaseEditTask(new UpdateAuthorReferenceReferencePositionEdit(this.authorReferenceReference.getReference().getReferenceID(),
            this.authorReferenceReference.getAuthorReference().getAuthorReferenceID(),
            ((SpinnerNumberModel)this.newPositionSpinner.getModel()).getNumber().intValue()), rootPane)).execute();
    
    dispose();
}//GEN-LAST:event_updateButtonActionPerformed

  /**
   * 
   * @param evt 
   */
  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    dispose();
}//GEN-LAST:event_cancelButtonActionPerformed

  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelButton;
  private javax.swing.JLabel newPositionDescriptionLabel;
  private javax.swing.JSpinner newPositionSpinner;
  private javax.swing.JSeparator separator;
  private javax.swing.JButton updateButton;
  // End of variables declaration//GEN-END:variables
  private AuthorReferenceReference authorReferenceReference;
}
