/*
 * AddDocumentDialog.java
 *
 * Created on 16-mar-2011, 14:22:38
 */
package scimat.gui.components.adddialog;

import javax.swing.JOptionPane;
import scimat.gui.commands.edit.add.AddReferenceEdit;
import scimat.gui.commands.task.PerformKnowledgeBaseEditTask;

/**
 *
 * @author mjcobo
 */
public class AddReferenceDialog extends javax.swing.JDialog {

  /** Creates new form AddDocumentDialog */
  public AddReferenceDialog(java.awt.Frame parent) {
    super(parent, true);
    initComponents();
  }

  /**
   *
   */
  public void refresh() {

    this.fullReferenceTextField.setText("");
    this.volumeTextField.setText("");
    this.issueTextField.setText("");
    this.pagesTextField.setText("");
    this.doiTextField.setText("");
    this.formatTextField.setText("");
    this.yearTextField.setText("");
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    addButton = new javax.swing.JButton();
    cancelButton = new javax.swing.JButton();
    jSeparator1 = new javax.swing.JSeparator();
    formatDescriptionLabel = new javax.swing.JLabel();
    formatTextField = new javax.swing.JTextField();
    fullReferenceDescriptionLabel = new javax.swing.JLabel();
    fullReferenceTextField = new javax.swing.JTextField();
    issueDescriptionLabel = new javax.swing.JLabel();
    issueTextField = new javax.swing.JTextField();
    volumeDescriptionLabel = new javax.swing.JLabel();
    volumeTextField = new javax.swing.JTextField();
    pagesDescriptionLabel = new javax.swing.JLabel();
    pagesTextField = new javax.swing.JTextField();
    yearDescriptionLabel = new javax.swing.JLabel();
    yearTextField = new javax.swing.JTextField();
    doiDescriptionLabel = new javax.swing.JLabel();
    doiTextField = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Add document");
    setAlwaysOnTop(true);
    setModal(true);

    addButton.setText("Add");
    addButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        addButtonActionPerformed(evt);
      }
    });

    cancelButton.setText("Cancel");
    cancelButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelButtonActionPerformed(evt);
      }
    });

    formatDescriptionLabel.setText("Format:");

    fullReferenceDescriptionLabel.setText("Full reference:");

    issueDescriptionLabel.setText("Issue:");

    volumeDescriptionLabel.setText("Volume:");

    pagesDescriptionLabel.setText("Pages:");

    yearDescriptionLabel.setText("Year:");

    doiDescriptionLabel.setText("Doi:");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(fullReferenceDescriptionLabel)
              .addComponent(issueDescriptionLabel)
              .addComponent(doiDescriptionLabel)
              .addComponent(formatDescriptionLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(doiTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(issueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(volumeDescriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(volumeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pagesDescriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pagesTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yearDescriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yearTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
              .addComponent(fullReferenceTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
              .addComponent(formatTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(addButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(cancelButton)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(fullReferenceDescriptionLabel)
          .addComponent(fullReferenceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
          .addComponent(issueDescriptionLabel)
          .addComponent(issueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(volumeDescriptionLabel)
          .addComponent(pagesDescriptionLabel)
          .addComponent(volumeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(pagesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(yearDescriptionLabel)
          .addComponent(yearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(doiDescriptionLabel)
          .addComponent(doiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(formatDescriptionLabel)
          .addComponent(formatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cancelButton)
          .addComponent(addButton))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * 
   * @param evt
   */
  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    dispose();
  }//GEN-LAST:event_cancelButtonActionPerformed

  /**
   * 
   * @param evt
   */
  private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed

    PerformKnowledgeBaseEditTask task;

    if (this.fullReferenceTextField.getText().isEmpty()) {

      JOptionPane.showMessageDialog(this, "You have to give a full reference.\nPlease, " +
        "give a full reference for the reference.", "Invalid full reference", JOptionPane.ERROR_MESSAGE);

    } else {

      task = new PerformKnowledgeBaseEditTask(new AddReferenceEdit(this.fullReferenceTextField.getText(),
              this.volumeTextField.getText(), this.issueTextField.getText(),
              this.pagesTextField.getText(), this.yearTextField.getText(),
              this.doiDescriptionLabel.getText(),
              this.formatTextField.getText()), rootPane);

      task.execute();

      if (task.isSuccessful()) {

        dispose();
      }
    }
  }//GEN-LAST:event_addButtonActionPerformed
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton addButton;
  private javax.swing.JButton cancelButton;
  private javax.swing.JLabel doiDescriptionLabel;
  private javax.swing.JTextField doiTextField;
  private javax.swing.JLabel formatDescriptionLabel;
  private javax.swing.JTextField formatTextField;
  private javax.swing.JLabel fullReferenceDescriptionLabel;
  private javax.swing.JTextField fullReferenceTextField;
  private javax.swing.JLabel issueDescriptionLabel;
  private javax.swing.JTextField issueTextField;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JLabel pagesDescriptionLabel;
  private javax.swing.JTextField pagesTextField;
  private javax.swing.JLabel volumeDescriptionLabel;
  private javax.swing.JTextField volumeTextField;
  private javax.swing.JLabel yearDescriptionLabel;
  private javax.swing.JTextField yearTextField;
  // End of variables declaration//GEN-END:variables
}
