/*
 * SelectDataReductionPerPeriod.java
 *
 * Created on 04-abr-2011, 15:48:20
 */
package scimat.gui.components.wizard.Analysis;

import java.util.ArrayList;
import javax.swing.GroupLayout.ParallelGroup;
import javax.swing.GroupLayout.SequentialGroup;
import scimat.model.knowledgebase.entity.Period;

/**
 *
 * @author mjcobo
 */
public class SelectNetworkReductionPerPeriod extends javax.swing.JPanel {

  /** Creates new form SelectDataReductionPerPeriod */
  public SelectNetworkReductionPerPeriod() {
    initComponents();
  }

  public void refresh(ArrayList<Period> periods) {

    int i;
    SelectPeriodNetworkReductionMethodPanel selectPeriodPreprocessingFunctionPanel;

    if (periods != null) {

      this.selectPeriodPreprocessingFunctionPanels = new SelectPeriodNetworkReductionMethodPanel[periods.size()];

      for (i = 0; i < periods.size(); i++) {

        selectPeriodPreprocessingFunctionPanel = new SelectPeriodNetworkReductionMethodPanel();
        selectPeriodPreprocessingFunctionPanel.setTitleToMainPanel(periods.get(i).getName());
        selectPeriodPreprocessingFunctionPanel.refresh();

        this.selectPeriodPreprocessingFunctionPanels[i] = selectPeriodPreprocessingFunctionPanel;
      }
      
      this.removeAll();

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);

      ParallelGroup parallelGroup;
      SequentialGroup sequentialGroup;


      parallelGroup = layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);

      for (i = 0; i < this.selectPeriodPreprocessingFunctionPanels.length; i++) {

        parallelGroup = parallelGroup.addComponent(selectPeriodPreprocessingFunctionPanels[i],
                javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE);
      }

      layout.setHorizontalGroup(parallelGroup);


      parallelGroup = layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);
      sequentialGroup = layout.createSequentialGroup();

      

      for (i = 0; i < this.selectPeriodPreprocessingFunctionPanels.length; i++) {

        sequentialGroup = sequentialGroup.addComponent(selectPeriodPreprocessingFunctionPanels[i],
                javax.swing.GroupLayout.PREFERRED_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.PREFERRED_SIZE);

        if (i < (this.selectPeriodPreprocessingFunctionPanels.length - 1)) {
          sequentialGroup.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED);
        }
      }

      parallelGroup.addGroup(sequentialGroup);
      layout.setVerticalGroup(parallelGroup);
      
    }
  }

  /**
   *
   * @return
   */
  public boolean isCoOccurrenceNetworkReductionSelected(int period) {

    return this.selectPeriodPreprocessingFunctionPanels[period].isCoOccurrenceNetworkReductionSelected();
  }

  /**
   *
   * @return
   */
  public int getMinCoOccurrenceNetworkReductionSelected(int period) {

    return (Integer)this.selectPeriodPreprocessingFunctionPanels[period].getMinCoOccurrenceNetworkReductionSelected();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 426, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 228, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
  private SelectPeriodNetworkReductionMethodPanel[] selectPeriodPreprocessingFunctionPanels;
}
